# Generated by Django 2.2.6 on 2019-10-14 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('founder', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(blank=True, default='M', max_length=1)),
                ('real_name', models.CharField(blank=True, default='', max_length=100)),
                ('publisher', models.ForeignKey(on_delete='cascade', to='superheroes.Publisher')),
            ],
            options={
                'ordering': ('hero_name',),
            },
        ),
    ]
